name: ci

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
        shell: bash
