name: ci

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
        shell: bash

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
        shell: bash

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
        shell: bash
