name: Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  recheck:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/recheck')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}

      - name: Trigger CI Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const workflow = workflows.workflows.find(wf => wf.name === 'ci');
            if (!workflow) {
              throw new Error('CI workflow not found');
            }

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              ref: context.payload.issue.pull_request.head.ref,
            });
